%%{init: {"theme":"base"}}%%
flowchart TD
    A[開始] --> B[讀取商圈 CSV 檔]
    
    B --> C{地址是否與商圈說明吻合?}
    
    C -->|是| D{地點是否為商圈?}
    D -->|是| E[使用地址]
    D -->|否| F{網頁照片是否有商圈?}
    F -->|有| G[使用網頁照片位置當作商圈地址]
    F -->|否| H[使用網頁照片地標或觀光區當作商圈地址]
    
    C -->|否| I{網頁照片是否有商圈?}
    I -->|是| J{是否與商圈說明吻合?}
    J -->|是| L[使用地址為商圈地址]
    J -->|否| K{是否有景觀或地標?}
    I -->|否| K
    K -->|是| M{是否與商圈說明吻合?}
    M -->|是| N[使用地址為商圈地址]
    M -->|否| O[使用地址為商圈地址，備註說明]
    K -->|否| O
    
    %% 最後檢查重複商圈
    E --> P[檢查是否有重複商圈]
    G --> P
    H --> P
    L --> P
    N --> P
    O --> P
    P --> Q{是否有重複?}
    Q -->|是| R[標註備註為「重複」]
    Q -->|否| S[不標註]
    
    R --> T[結束]
    S --> T
